config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  get 'home/index'
  devise_for :users
  get "/" => "home#top"
  root :to => "home#top"
  get "index" => "posts#index"
  resources :posts
  resources :friends
  resources :profiles
  resources :vaccinations
  resources :medicines
  resources :home
  root 'home#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/medicine.rb
class Medicine < ApplicationRecord
  validates :drug, presence: true
  validates :date, presence: true
  belongs_to :profile
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :weight, presence: true
  belongs_to :profile
  belongs_to :user
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :destroy
  has_many :medicines, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  validates :email, presence: true
  has_many :posts
  has_many :vaccinations
  has_many :medicines
  has_many :friends
  has_many :profiles

end

app/models/vaccination.rb
class Vaccination < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:nickname])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:accont_update, keys: [:nickname])
  end

  def after_sign_in_path_for(resource)
    index_path # ログイン後に遷移するpathを設定
  end


end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :authenticate_user!

  def index
    @friends = current_user.friends.all
  end

  def new
  end

  def create
    @friend = current_user.friends.new(friend_params)
    @friend.save
    redirect_to friends_path
  end

  def destroy
    @friend = current_user.friends.find(params[:id])
    @friend.destroy
    redirect_to friends_path
  end

  def edit
    @friend = current_user.friends.find(params[:id])
  end

  def update
    @friend = current_user.friends.find(params[:id])
    @friend.update(friend_params)
    redirect_to friends_path
  end

  private
    def friend_params
      params.require(:friend).permit(:name, :breed, :gender, :owner, :coat, :feature, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  def index
  end
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  before_action :authenticate_user!

  def index
    @medicines = current_user.medicines.all.order(created_at: 'desc')
  end

  def new
    @medicine = current_user.medicines.new
    @profiles = current_user.profiles.all
  end

  def create
    @medicine = current_user.medicines.new(medicine_params)
    @profiles = current_user.profiles.all
    if @medicine.save
      redirect_to medicines_path
    else
      render 'new'
    end
  end

  def destroy
    @medicine = current_user.medicines.find(params[:id])
    @profiles = current_user.profiles.all
    @medicine.destroy
    redirect_to medicines_path
  end

  def edit
    @medicine = current_user.medicines.find(params[:id])
    @profiles = current_user.profiles.all
  end

  def update
    @medicine = current_user.medicines.find(params[:id])
    @profiles = current_user.profiles.all
    @medicine.update(medicine_params)
    redirect_to medicines_path
  end

  private
    def medicine_params
      params.require(:medicine).permit(:drug, :date, :name, :profile_id, :user_id)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = current_user.posts.all.order(created_at: 'desc')
  end

  def new
    @post = current_user.posts.new
    @profiles = current_user.profiles.all
  end

  def create
    @post = current_user.posts.new(post_params)
    @profiles = current_user.profiles.all
    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @profiles = current_user.profiles.all
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:date, :weight, :difference, :profile_id, :user_id)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def index
    @profiles = current_user.profiles.all
  end

  def new
  end

  def create
    @profile = current_user.profiles.new(profile_params)
    @profile.save
    redirect_to profiles_path
  end

  def destroy
    @profile = current_user.profiles.find(params[:id])
    @profile.destroy
    redirect_to profiles_path
  end

  def edit
    @profile = current_user.profiles.find(params[:id])
  end

  def update
    @profile = current_user.profiles.find(params[:id])
    @profile.update(profile_params)
    redirect_to profiles_path
  end

  private
    def profile_params
      params.require(:profile).permit(:name, :birthday, :gender, :birthweight, :birthplace, :walk, :food, :trick, :character, :operation, :test, :history, :illness, :user_id)
    end

end

app/controllers/vaccinations_controller.rb
class VaccinationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @vaccinations = current_user.vaccinations.all.order(created_at: 'desc')
  end

  def new
  end

  def create
    @vaccination = current_user.vaccinations.new(vaccination_params)
    @vaccination.save
    redirect_to vaccinations_path
  end

  def destroy
    @vaccination = current_user.vaccinations.find(params[:id])
    @vaccination.destroy
    redirect_to vaccinations_path
  end

  def edit
    @vaccination = current_user.vaccinations.find(params[:id])
  end

  def update
    @vaccination = current_user.vaccinations.find(params[:id])
    @vaccination.update(vaccination_params)
    redirect_to vaccinations_path
  end

  private
    def vaccination_params
      params.require(:vaccination).permit(:date, :rabies, :vaccine, :filaria, :flea, :user_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/vaccination_helper.rb
module VaccinationHelper
end

app/views/friends/edit.html.erb
<h4><span class="hitokoto1"><i class="fas fa-user-friends"></i>お友達を編集する</span></h4>

<%= form_for @friend, url: friend_path(@friend) do |f| %>
<div class="field friend-field">
  <%= f.label :犬の名前 %><br>
  <%= f.text_field :name, :class => 'form-control form-friend-1' %>
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="field friend-field">
  <%= f.label :性別 %><br>
  <%= f.select :gender, [['オス', 'オス'], ['メス', 'メス']], :class => 'form-control form-friend-2' %>
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="field friend-field">
  <%= f.label :犬種 %><br>
  <%= f.text_field :breed, :class => 'form-control form-friend-3' %>
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="field friend-field">
  <%= f.label :飼い主 %><br>
  <%= f.text_field :owner, placeholder: "例)山田さん、ひとみちゃん", :class => 'form-control form-friend-4' %>
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="field friend-field">
  <%= f.label :毛色 %><br>
  <%= f.text_field :coat, placeholder: "例)茶", :class => 'form-control form-friend-5' %>
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="field friend-field">
  <%= f.label :特徴 %><br>
  <%= f.text_area :feature, placeholder: "例)飼い主さんの特徴、ワンちゃんの服・首輪など", :class => 'form-control form-friend-6' %>
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="actions">
  <%= f.submit '登録する', :class=>'btn-primary' %>
</div>

<div class="return">
  <a><%= link_to 'もどる', friends_path, class: "square_btn" %></a>
</div>

<% end %>

app/views/friends/index.html.erb
<div class="inindex">

<div class="cursor">
  <ul class="index_list">
   <li class="friend_index_list_1"><%= link_to posts_path do %>体重測定<br><i class="fas fa-weight"></i></li><% end %>
   <li class="friend_index_list_2"><%= link_to vaccinations_path do %>予防接種<br><i class="fas fa-syringe"></i></li><% end %>
   <li class="friend_index_list_3"><%= link_to medicines_path do %>投薬状況<br><i class="fas fa-capsules"></i></li><% end %>
   <li class="friend_index_list_4"><%= link_to friends_path do %>お友だち<br><i class="fas fa-user-friends"></i></li><% end %>
   <li class="friend_index_list_5"><%= link_to profiles_path do %>愛犬紹介<br><i class="fas fa-bone"></i></li><% end %>
  </ul>
</div>

<p><span class="hitokoto"><i class="fas fa-user-friends"></i>お知り合いになったワンちゃんのリスト</span></p>

<div class="sokutei">
  <%= link_to "新規登録", new_friend_path, class: "btn-primary-f" %>
</div>

<table class="friend_index_table"　border="1">
  <tr>
    <th style="color:#ab3e16">犬の名前</th>
    <th>性別</th>
    <th>飼い主</th>
    <th rowspan="2">特徴</th>
    <th rowspan="2"></th>
  </tr>
  <tr>
    <th colspan="2">犬 種</th>
    <th>毛色</th>
  </tr>
  <% @friends.each do |friend| %>    　
  <tr style="border-top: solid 2px #e7cc8f;">
    <td style="color:#ab3e16"><%= friend.name %></td>
    <td><%= friend.gender %></td>
    <td><%= friend.owner %></td>
    <td rowspan="2"><%= friend.feature %></td>
    <td><%= link_to '編集する', edit_friend_path(friend.id), class: "square_btn_sm" %></td>
    </tr>
  <tr>
    <td colspan="2"><%= friend.breed %></td>
    <td><%= friend.coat %></td>
    <td><%= link_to '削除する', friend_path(friend.id), method: :delete, class: "square_btn_sm", data: { confirm: '本当に削除しますか？' } %></td>
  </tr>
  <% end %>

</table>
</div>

app/views/home/index.html.erb
<div class="cursor">
  <ul class="index_list">
   <li class="index_list_1"><a href="#">体重測定<br><i class="fas fa-weight"></i></a></li>
   <li class="index_list_2"><a href="#">予防接種<br><i class="fas fa-syringe"></i></a></li>
   <li class="index_list_3"><a href="#">投薬状況<br><i class="fas fa-capsules"></i></a></li>
   <li class="index_list_4"><a href="#">お友だち<br><i class="fas fa-user-friends"></i></a></li>
   <li class="index_list_5"><a href="#">アルバム<br><i class="far fa-images"></i></a></li>
  </ul>
</div>

<p class="hitokoto"><i class="fas fa-weight"></i>今日も、愛犬の体重測定から始めましょう</p>

<div class="sokutei">
  <a href="#" class="square_btn">測定する</a>
</div>

<table class="index_table"　border="1">
  <tr>
    <th>測定日</th>
    <th>体重(Kg)</th>
    <th>前回との差</th>
  </tr>
  <tr>
    <td>2019/01/01</td>
    <td>1</td>
    <td>1</td>
  </tr>
  <tr>
    <td>2019/01/01</td>
    <td>1</td>
    <td>1</td>
  </tr>
  <tr>
    <td>2019/01/01</td>
    <td>1</td>
    <td>1</td>
  </tr>
  <tr>
    <td>2019/01/01</td>
    <td>1</td>
    <td>1</td>
  </tr>
</table>

app/views/medicines/edit.html.erb
<h4><span class="hitokoto1"><i class="fas fa-capsules"></i>お薬を編集する</span></h4>

<%= form_for @medicine, url: medicine_path(@medicine) do |f| %>

<div class="field medicine-field">
  <%= f.label :投薬日 %><br>
  <%= f.date_select :date, :use_month_numbers => true, :start_year =>2010, :end_year =>2030, :date_separator => "/", :size => 1000, :class => 'form-control medicine-2' %>
</div>

<div class="field medicine-field">
  <%= f.label :病名 %><br>
  <%= f.text_field :drug, :class => 'form-control form-medicine-1' %>
</div>

<div class="field medicine-field">
  <%= f.label :登録した愛犬を選択してください %><br>
  <%= f.collection_select :profile_id, @profiles, :id, :name, :class => 'form-control form-medicine-1' %>
</div>

<div class="actions">
  <%= f.submit '登録する', :class=>'btn-primary' %>
</div>

<div class="delete">
  <%= link_to '削除する', medicine_path(@medicine.id), method: :delete, class: 'btn-primary', data: { confirm: '本当に削除しますか？' } %>
</div>

<div class="return">
  <a><%= link_to 'もどる', medicines_path, class: "square_btn" %></a>
</div>
<% end %>

app/views/medicines/index.html.erb
<div class="inindex">

<div class="cursor">
  <ul class="index_list">
   <li class="medicine_index_list_1"><%= link_to posts_path do %>体重測定<br><i class="fas fa-weight"></i></li><% end %>
   <li class="medicine_index_list_2"><%= link_to vaccinations_path do %>予防接種<br><i class="fas fa-syringe"></i></li><% end %>
   <li class="medicine_index_list_3"><%= link_to medicines_path do %>投薬状況<br><i class="fas fa-capsules"></i></li><% end %>
   <li class="medicine_index_list_4"><%= link_to friends_path do %>お友だち<br><i class="fas fa-user-friends"></i></li><% end %>
   <li class="medicine_index_list_5"><%= link_to profiles_path do %>愛犬紹介<br><i class="fas fa-bone"></i></li><% end %>
  </ul>
</div>

<p><span class="hitokoto"><i class="fas fa-capsules"></i>処方されたお薬一覧</span></p>

<div class="sokutei">
  <%= link_to "お薬登録", new_medicine_path, class: "btn-primary-f" %>
</div>

<table class="medicine_index_table"　border="1">
  <tr>
    <th>投薬日</th>
    <th>病名・薬名</th>
    <th>患者(犬)</th>
    <th></th>
  </tr>
    <% @medicines.each do |medicine| %>
  <tr>
    <td><%= medicine.date %></td>
    <td><%= medicine.drug %></td>
    <td><%= medicine.profile.name %></td>
    <td><%= link_to '編集する', edit_medicine_path(medicine.id), class: "square_btn_sm" %></td>
  </tr>
  <% end %>

</table>
</div>

app/views/posts/index.html.erb
<div class="inindex">

<div class="cursor">
  <ul class="index_list">
   <li class="index_list_1"><%= link_to posts_path do %>体重測定<br><i class="fas fa-weight"></i></li><% end %>
   <li class="index_list_2"><%= link_to vaccinations_path do %>予防接種<br><i class="fas fa-syringe"></i></li><% end %>
   <li class="index_list_3"><%= link_to medicines_path do %>投薬状況<br><i class="fas fa-capsules"></i></li><% end %>
   <li class="index_list_4"><%= link_to friends_path do %>お友だち<br><i class="fas fa-user-friends"></i></li><% end %>
   <li class="index_list_5"><%= link_to profiles_path do %>愛犬紹介<br><i class="fas fa-bone"></i></li><% end %>
  </ul>
</div>

<p><span class="hitokoto"><i class="fas fa-weight"></i>今日も、愛犬の体重測定から始めましょう</span></p>

<div class="sokutei">
  <%= link_to "測定する", new_post_path, class: "btn-primary-f" %>
</div>


<table class="index_table"　border="1">
  <tr>
    <th>測定日</th>
    <th>犬の名前</th>
    <th>体重(Kg)</th>
    <th></th>
  </tr>
  <% @posts.each do |post| %>    　
  <tr>
    <td><%= post.date %></td>
    <td><%= post.profile.name %></td>
    <td><%= post.weight %></td>
    <td><%= link_to '削除する', post_path(post.id) , method: :delete, class: "square_btn_sm", data: { confirm: '本当に削除しますか？' } %></td>
  </tr>
  <% end %>

</table>


</div>

app/views/profiles/edit.html.erb
<h4><span class="hitokoto1"><i class="fas fa-bone"></i>愛犬を編集する</span></h4>

<%= form_for @profile, url: profile_path(@profile) do |f| %>
<div class="field profile-field">
  <%= f.label :名前 %><br>
  <%= f.text_field :name, :class => 'form-control form-profile-1' %>
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="field profile-field">
  <%= f.label :生年月日 %><a style="color:red;">：半角で入力してください</a><br>
  <%= f.text_field :birthday, placeholder: "例)2019/1/1", :class => 'form-control form-profile-2' %>
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="field profile-field">
  <%= f.label :性別 %><br>
  <%= f.select :gender, [['オス', 'オス'], ['メス', 'メス']], :class => 'form-control form-profile-3' %>
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="field profile-field">
  <%= f.label :出生体重 %><br>
  <%= f.number_field :birthweight, placeholder: "例)3.5", step: "0.01", :class => 'form-control form-profile-4' %>Kg
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="field profile-field">
  <%= f.label :出生地 %><br>
  <%= f.text_field :birthplace, :class => 'form-control form-profile-5' %>
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="field profile-field">
  <%= f.label :散歩量 %><br>
  <%= f.text_field :walk, placeholder: "例)朝30分　夕30分", :class => 'form-control form-profile-6' %>
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="field profile-field">
  <%= f.label :好物 %><br>
  <%= f.text_field :food, placeholder: "例)りんご", :class => 'form-control form-profile-7' %>
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="field profile-field">
  <%= f.label :芸 %><br>
  <%= f.text_field :trick, placeholder: "例)ふせ", :class => 'form-control form-profile-8' %>
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="field profile-field">
  <%= f.label :性格 %><br>
  <%= f.text_area :character, placeholder: "例)人懐っこい", :class => 'form-control form-profile-9' %>
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="field profile-field">
  <%= f.label :現病歴 %><br>
  <%= f.text_area :illness, placeholder: "例)糖尿病", :class => 'form-control form-profile-10' %>
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="field profile-field">
  <%= f.label :既往歴 %><br>
  <%= f.text_area :history, placeholder: "例)アトピー", :class => 'form-control form-profile-11' %>
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="field profile-field">
  <%= f.label :検査記録 %><br>
  <%= f.text_area :test, placeholder: "例)MRI", :class => 'form-control form-profile-12' %>
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="field profile-field">
  <%= f.label :手術記録 %><br>
  <%= f.text_area :operation, placeholder: "例)去勢", :class => 'form-control form-profile-13' %>
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="actions">
  <%= f.submit '登録する', :class=>'btn-primary' %>
</div>

<div class="delete">
  <%= link_to '削除する', profile_path(@profile.id), method: :delete, class: 'btn-primary', data: { confirm: '本当に削除しますか？' } %>
</div>

<div class="return">
  <a><%= link_to 'もどる', profiles_path, class: "square_btn" %></a>
</div>
<% end %>

app/views/profiles/index.html.erb
<div class="inindex">

<div class="cursor">
  <ul class="index_list">
   <li class="profile_index_list_1"><%= link_to posts_path do %>体重測定<br><i class="fas fa-weight"></i></li><% end %>
   <li class="profile_index_list_2"><%= link_to vaccinations_path do %>予防接種<br><i class="fas fa-syringe"></i></li><% end %>
   <li class="profile_index_list_3"><%= link_to medicines_path do %>投薬状況<br><i class="fas fa-capsules"></i></li><% end %>
   <li class="profile_index_list_4"><%= link_to friends_path do %>お友だち<br><i class="fas fa-user-friends"></i></li><% end %>
   <li class="profile_index_list_5"><%= link_to profiles_path do %>愛犬紹介<br><i class="fas fa-bone"></i></li><% end %>
  </ul>
</div>

<p><span class="hitokoto"><i class="fas fa-bone"></i>ワンちゃん達のプロフィール</span></p>

<div class="sokutei">
  <%= link_to "愛犬登録", new_profile_path, class: "btn-primary-f" %>
</div>

<table class="profile_index_table"　border="1">
  <tr>
    <td>名 前</td>
    <% @profiles.each do |profile| %>
    <td style="color:#ab3e16"><%= profile.name %>  <%= link_to '編集する', edit_profile_path(profile.id), class: "square_btn_sm" %></td>
    <% end %>
  </tr>
  <tr>
    <td>生年月日</td>
    <% @profiles.each do |profile| %>
    <td><%= profile.birthday %></td>
    <% end %>
  </tr>
  <tr>
    <td>性 別</td>
    <% @profiles.each do |profile| %>
    <td><%= profile.gender %></td>
    <% end %>
  </tr>
  <tr>
    <td>出生体重</td>
    <% @profiles.each do |profile| %>
    <td><%= profile.birthweight %></td>
    <% end %>
  </tr>
  <tr>
    <td>出生地</td>
    <% @profiles.each do |profile| %>
    <td><%= profile.birthplace %></td>
    <% end %>
  </tr>
  <tr>
    <td>散歩量</td>
    <% @profiles.each do |profile| %>
    <td><%= profile.walk %></td>
    <% end %>
  </tr>
  <tr>
    <td>好 物</td>
    <% @profiles.each do |profile| %>
    <td><%= profile.food %></td>
    <% end %>
  </tr>
  <tr>
    <td>芸</td>
    <% @profiles.each do |profile| %>
    <td><%= profile.trick %></td>
    <% end %>
  </tr>
  <tr>
    <td>性 格</td>
    <% @profiles.each do |profile| %>
    <td><%= profile.character %></td>
    <% end %>
  </tr>
  <tr>
    <td>現病歴</td>
    <% @profiles.each do |profile| %>
    <td><%= profile.illness %></td>
    <% end %>
  </tr>
  <tr>
    <td>既往歴</td>
    <% @profiles.each do |profile| %>
    <td><%= profile.history %></td>
    <% end %>
  </tr>
  <tr>
    <td>検査記録</td>
    <% @profiles.each do |profile| %>
    <td><%= profile.test %></td>
    <% end %>
  </tr>
  <tr>
    <td>手術記録</td>
    <% @profiles.each do |profile| %>
    <td><%= profile.operation %></td>
    <% end %>
  </tr>

</table>
</div>

app/views/vaccinations/edit.html.erb
<h4><span class="hitokoto1"><i class="fas fa-syringe"></i>予防接種を編集する</span><br><a style="color:red; font-weight:normal;">半角で入力してください</a></h4>

<%= form_for @vaccination, url: vaccination_path(@vaccination) do |f| %>

<div class="field vaccination-field">
  <%= f.label :狂犬病 %><br>
  <%= f.text_field :rabies, placeholder: "例)2019/1/1", :class => 'form-control form-profile-2' %>
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="field vaccination-field">
  <%= f.label :混合ワクチン %><br>
  <%= f.text_field :vaccine, placeholder: "例)2019/1/1", :class => 'form-control form-profile-2' %>
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="field vaccination-field">
  <%= f.label :フィラリア %><br>
  <%= f.text_field :filaria, placeholder: "例)2019/1/1", :class => 'form-control form-profile-2' %>
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="field vaccination-field">
  <%= f.label :ノミ・ダニ %><br>
  <%= f.text_field :flea, placeholder: "例)2019/1/1", :class => 'form-control form-profile-2' %>
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

<div class="actions">
  <%= f.submit '登録する', :class=>'btn-primary' %>
</div>

<div class="delete">
  <%= link_to '削除する', vaccination_path(@vaccination.id), method: :delete, class: 'btn-primary', data: { confirm: '本当に削除しますか？' } %>
</div>

<div class="return">
  <a><%= link_to 'もどる', vaccinations_path, class: "square_btn" %></a>
</div>

<% end %>

app/views/vaccinations/index.html.erb
<div class="inindex">

<div class="cursor">
  <ul class="index_list">
   <li class="vaccination_index_list_1"><%= link_to posts_path do %>体重測定<br><i class="fas fa-weight"></i></li><% end %>
   <li class="vaccination_index_list_2"><%= link_to vaccinations_path do %>予防接種<br><i class="fas fa-syringe"></i></li><% end %>
   <li class="vaccination_index_list_3"><%= link_to medicines_path do %>投薬状況<br><i class="fas fa-capsules"></i></li><% end %>
   <li class="vaccination_index_list_4"><%= link_to friends_path do %>お友だち<br><i class="fas fa-user-friends"></i></li><% end %>
   <li class="vaccination_index_list_5"><%= link_to profiles_path do %>愛犬紹介<br><i class="fas fa-bone"></i></li><% end %>
  </ul>
</div>

<p><span class="hitokoto"><i class="fas fa-syringe"></i>定期的に接種して予防に努めましょう</span></p>

<div class="sokutei">
  <%= link_to "接種日追加", new_vaccination_path, class: "btn-primary-f" %>
</div>

<table class="vaccination_index_table"　border="1">
  <tr>
    <th>狂犬病</th>
    <th>ワクチン</th>
    <th>フィラリア</th>
    <th>ノミ・ダニ</th>
    <th></th>
  </tr>
  <% @vaccinations.each do |vaccination| %>    　
  <tr>
    <td><%= vaccination.rabies %></td>
    <td><%= vaccination.vaccine %></td>
    <td><%= vaccination.filaria %></td>
    <td><%= vaccination.flea %></td>
    <td><%= link_to '編集する', edit_vaccination_path(vaccination.id), class: "square_btn_sm_vaccination"  %></td>
  </tr>
  <% end %>

</table>
</div>